%CLF
MPF 69
%M30

%MPF 69
(************************)
(PROYECTO:  WinDNC para fresa)
(ARCHIVO:   GRAFICO1.CNC)
(AUTOR:     Eugenio Lopez G.)
(FECHA:     21/ENE/1999)
(************************)

G71 (medidas en milimetros)
G55 G94
R1=-16.100
G53 G00 Z300.

T01 D01 L96
M03 S1000 F500
G00 Z-5.100
G00 X-92.024 Y108.433
G01 Z=R1
G01 X68.936 Y-57.353

G71(mm) G94(minute)
G53 G00 Z300.
G53 G00 X216.
G53 G00 Y327.
M30


